import { PUZZLES } from './puzzles.js'

// Per-puzzle [meaning, clue, example translation] in each language. Serbian has no example translation (the example is already Serbian).
// Not yet checked by native speakers.
const TR = {
  1: { sr: ['osećam ljubav ili simpatiju', 'Dve reči koje pošalješ kad ti je stvarno stalo: "___ te."'], fr: ["j'aime / je t'aime", 'Deux mots que tu écris quand tu tiens vraiment à quelqu’un : « ___ te. »', "Je t'aime."], es: ['amo / me gusta', 'Dos palabras que escribes cuando alguien te importa de verdad: «___ te».', 'Te quiero.'], vi: ['yêu / thích', 'Hai từ bạn nhắn khi thật sự quan tâm ai đó: "___ te."', 'Mình yêu bạn.'] },
  2: { sr: ['izraz zahvalnosti', 'Ljubazno kažeš kad ti neko pomogne.'], fr: ['merci', 'Ce qu’on dit poliment quand quelqu’un nous aide.', 'Merci beaucoup.'], es: ['gracias', 'Lo que se dice con educación cuando alguien te ayuda.', 'Muchas gracias.'], vi: ['cảm ơn', 'Điều lịch sự nói khi ai đó giúp bạn.', 'Cảm ơn bạn rất nhiều.'] },
  3: { sr: ['ovaj dan', 'Ni juče, ni sutra.'], fr: ["aujourd'hui", 'Ni hier, ni demain.', "Qu'est-ce que tu fais aujourd'hui ?"], es: ['hoy', 'Ni ayer ni mañana.', '¿Qué haces hoy?'], vi: ['hôm nay', 'Không phải hôm qua, cũng không phải ngày mai.', 'Hôm nay bạn làm gì?'] },
  4: { sr: ['sledeći dan', 'Dan posle današnjeg.'], fr: ['demain', 'Le jour après aujourd’hui.', 'On se voit demain.'], es: ['mañana (el día siguiente)', 'El día después de hoy.', 'Nos vemos mañana.'], vi: ['ngày mai', 'Ngày sau hôm nay.', 'Hẹn gặp bạn ngày mai.'] },
  5: { sr: ['vreme od rođenja do smrti', 'Ono što upravo živiš.'], fr: ['la vie', 'Ce que tu vis en ce moment.', 'La vie est belle.'], es: ['la vida', 'Lo que estás viviendo ahora mismo.', 'La vida es bella.'], vi: ['cuộc sống', 'Điều bạn đang sống ngay lúc này.', 'Cuộc sống thật đẹp.'] },
  6: { sr: ['osećaj zadovoljstva; slučaj koji ide u prilog', 'Ono što poželiš nekome pred ispit ili put.'], fr: ['chance / bonheur', 'Ce qu’on souhaite à quelqu’un avant un examen ou un voyage.', 'Le bonheur est dans les petites choses.'], es: ['suerte / felicidad', 'Lo que se le desea a alguien antes de un examen o un viaje.', 'La felicidad está en las pequeñas cosas.'], vi: ['may mắn / hạnh phúc', 'Điều bạn chúc ai đó trước kỳ thi hay chuyến đi.', 'Hạnh phúc nằm trong những điều nhỏ bé.'] },
  7: { sr: ['pripovest; razgovor', 'Nešto što se priča, ili dug razgovor.'], fr: ['histoire / discussion', 'Quelque chose qu’on raconte, ou une longue conversation.', 'Quelle histoire !'], es: ['historia / charla', 'Algo que se cuenta, o una conversación larga.', '¡Qué historia!'], vi: ['câu chuyện / cuộc trò chuyện', 'Thứ người ta kể, hoặc một cuộc trò chuyện dài.', 'Thật là một câu chuyện!'] },
  8: { sr: ['mesto gde se pije kafa', 'Gde Beograd provodi popodneva.'], fr: ['café / bar', 'Là où Belgrade passe ses après-midi.', 'On se voit au café.'], es: ['cafetería / bar', 'Donde Belgrado pasa las tardes.', 'Nos vemos en el café.'], vi: ['quán cà phê / quán bar', 'Nơi Belgrade dành những buổi chiều.', 'Hẹn gặp bạn ở quán cà phê.'] },
  9: { sr: ['sat i vremenske prilike', 'Ista reč za sat i za vremensku prognozu.'], fr: ['temps / météo', 'Un seul mot pour l’horloge et la météo.', 'Quel temps fait-il aujourd’hui ?'], es: ['tiempo / clima', 'Una sola palabra para el reloj y el pronóstico.', '¿Qué tiempo hace hoy?'], vi: ['thời gian / thời tiết', 'Một từ cho cả đồng hồ lẫn dự báo thời tiết.', 'Hôm nay thời tiết thế nào?'] },
  10: { sr: ['ljubazna molba ili "kako, molim?"', 'Često ide uz "te" kad nešto tražiš.'], fr: ["s'il te plaît / pardon ?", 'Souvent suivi de « te » quand on demande quelque chose.', "S'il te plaît, aide-moi."], es: ['por favor / ¿perdón?', 'Suele ir con «te» cuando pides algo.', 'Por favor, ayúdame.'], vi: ['làm ơn / xin nhắc lại', 'Thường đi với "te" khi bạn nhờ vả.', 'Làm ơn, giúp tôi với.'] },
  11: { sr: ['ženski roditelj', 'Žena koja te je rodila.'], fr: ['mère', 'La femme qui t’a donné la vie.', "J'aime ma mère."], es: ['madre', 'La mujer que te dio la vida.', 'Quiero a mi madre.'], vi: ['mẹ', 'Người phụ nữ đã sinh ra bạn.', 'Tôi yêu mẹ của tôi.'] },
  12: { sr: ['u redu; nije loše', 'Odgovor na "Kako si?" kad je sve u redu.'], fr: ["bien / bon / d'accord", 'La réponse à « Kako si ? » quand tout va bien.', 'Tout va bien.'], es: ['bien / bueno / vale', 'La respuesta a «Kako si?» cuando todo va bien.', 'Todo está bien.'], vi: ['tốt / ổn / được', 'Câu trả lời cho "Kako si?" khi mọi thứ đều ổn.', 'Mọi thứ đều ổn.'] },
  13: { sr: ['večeras ili prošle noći', 'Ono što pitaš kad želiš da znaš plan za noć.'], fr: ['ce soir / cette nuit', 'Ce qu’on demande pour connaître le programme de la nuit.', "Qu'est-ce que tu fais ce soir ?"], es: ['esta noche / anoche', 'Lo que preguntas para saber el plan de la noche.', '¿Qué haces esta noche?'], vi: ['tối nay / đêm qua', 'Điều bạn hỏi khi muốn biết kế hoạch buổi tối.', 'Tối nay bạn làm gì?'] },
  14: { sr: ['početak dana', 'Prvi deo dana. "Dobro ___!"'], fr: ['matin', 'Le début de la journée. « Dobro ___ ! »', 'Bonjour !'], es: ['mañana (parte del día)', 'La primera parte del día. «Dobro ___!»', '¡Buenos días!'], vi: ['buổi sáng', 'Phần đầu của ngày. "Dobro ___!"', 'Chào buổi sáng!'] },
  15: { sr: ['fotografija ili crtež', 'Šta tražiš u poruci kad želiš nešto da vidiš.'], fr: ['image / photo', 'Ce que tu demandes dans un message pour voir quelque chose.', 'Envoie-moi une photo.'], es: ['imagen / foto', 'Lo que pides en un mensaje cuando quieres ver algo.', 'Mándame una foto.'], vi: ['hình ảnh / ảnh', 'Thứ bạn xin trong tin nhắn khi muốn xem gì đó.', 'Gửi cho tôi một tấm ảnh.'] },
  16: { sr: ['bela tečnost koju daju krave', 'Ide u kafu.'], fr: ['lait', 'Il va dans ton café.', 'Achète du lait.'], es: ['leche', 'Va en tu café.', 'Compra leche.'], vi: ['sữa', 'Thứ cho vào cà phê của bạn.', 'Mua sữa nhé.'] },
  17: { sr: ['ispravno; baš tako', 'Način da kažeš da je neko u pravu.'], fr: ['exactement / correct', 'Une façon de dire que c’est juste.', 'Exactement !'], es: ['exacto / correcto', 'Una forma de decir que está bien.', '¡Exacto!'], vi: ['chính xác / đúng', 'Cách nói rằng ai đó nói đúng.', 'Chính xác!'] },
  18: { sr: ['verovatno, nije sigurno', 'Ni da, ni ne.'], fr: ['peut-être', 'Ni oui, ni non.', 'Peut-être demain.'], es: ['quizás', 'Ni sí, ni no.', 'Quizás mañana.'], vi: ['có lẽ', 'Không phải có, cũng không phải không.', 'Có lẽ ngày mai.'] },
  19: { sr: ['u velikoj meri; puno', 'Pojačava svako "hvala".'], fr: ['beaucoup / très', 'Elle renforce n’importe quel merci.', 'Merci beaucoup !'], es: ['mucho / muy', 'Hace más fuerte cualquier gracias.', '¡Muchas gracias!'], vi: ['rất nhiều', 'Làm cho mọi lời cảm ơn thêm đậm đà.', 'Cảm ơn rất nhiều!'] },
  20: { sr: ['mnogo puta; ne retko', 'Više od "ponekad".'], fr: ['souvent', 'Plus que parfois.', 'Je pense souvent à toi.'], es: ['a menudo', 'Más que a veces.', 'Pienso en ti a menudo.'], vi: ['thường xuyên', 'Nhiều hơn "thỉnh thoảng".', 'Tôi thường nghĩ về bạn.'] },
  21: { sr: ['posle predviđenog vremena', 'Suprotno od "rano".'], fr: ['tard', 'Le contraire de « rano » (tôt).', 'Il est tard.'], es: ['tarde', 'Lo contrario de «rano» (temprano).', 'Es tarde.'], vi: ['muộn', 'Trái nghĩa của "rano" (sớm).', 'Muộn rồi.'] },
  22: { sr: ['malom brzinom', 'Šta tražiš od nekoga ko brzo govori.'], fr: ['lentement', 'Ce que tu demandes à quelqu’un qui parle vite.', "Parle lentement, s'il te plaît."], es: ['despacio', 'Lo que le pides a alguien que habla rápido.', 'Habla despacio, por favor.'], vi: ['chậm', 'Điều bạn nhờ người nói nhanh.', 'Làm ơn nói chậm thôi.'] },
  23: { sr: ['voljena žena (obraćanje)', 'Nežan način da se obratiš njoj.'], fr: ['chérie (à une femme)', 'Une façon tendre de s’adresser à elle.', 'Bonne nuit, chérie.'], es: ['querida (a una mujer)', 'Una forma cariñosa de dirigirte a ella.', 'Buenas noches, querida.'], vi: ['em yêu (nói với phụ nữ)', 'Một cách gọi âu yếm dành cho cô ấy.', 'Chúc ngủ ngon, em yêu.'] },
  24: { sr: ['deo tela iznad vrata', 'Gde stanuje glavobolja.'], fr: ['tête', 'Là où habite le mal de tête.', "J'ai mal à la tête."], es: ['cabeza', 'Donde vive el dolor de cabeza.', 'Me duele la cabeza.'], vi: ['đầu', 'Nơi cơn đau đầu trú ngụ.', 'Tôi bị đau đầu.'] },
  25: { sr: ['stojim i čekam', 'Šta pošalješ kad stojiš napolju.'], fr: ["j'attends", 'Ce que tu envoies quand tu es dehors.', "Je t'attends dehors."], es: ['espero', 'Lo que mandas cuando estás afuera.', 'Te espero afuera.'], vi: ['tôi đang đợi', 'Điều bạn nhắn khi đang đứng bên ngoài.', 'Tôi đang đợi bạn ở ngoài.'] },
  26: { sr: ['krećemo; hajde', 'Često sledi "na kafu?"'], fr: ["on y va / allons-y", 'Souvent suivi de « na kafu ? »', 'On va prendre un café ?'], es: ['vamos', 'A menudo seguido de «na kafu?»', '¿Vamos a tomar un café?'], vi: ['mình đi / đi nào', 'Thường theo sau là "na kafu?"', 'Mình đi uống cà phê nhé?'] },
  27: { sr: ['hoću; poželim', 'Šta činiš nekome na rođendan.'], fr: ['je souhaite / je veux', 'Ce qu’on fait pour l’anniversaire de quelqu’un.', 'Je te souhaite le meilleur.'], es: ['deseo / quiero', 'Lo que haces en el cumpleaños de alguien.', 'Te deseo lo mejor.'], vi: ['tôi chúc / tôi muốn', 'Điều bạn làm vào sinh nhật ai đó.', 'Chúc bạn mọi điều tốt đẹp nhất.'] },
  28: { sr: ['ima smisao', 'Pitaš o reči koju ne znaš: "Šta to ___?"'], fr: ['signifie', 'Tu le demandes pour un mot inconnu : « Šta to ___ ? »', "Qu'est-ce que ça veut dire ?"], es: ['significa', 'Lo preguntas sobre una palabra que no conoces: «Šta to ___?»', '¿Qué significa eso?'], vi: ['có nghĩa là', 'Bạn hỏi về từ mình không biết: "Šta to ___?"', 'Điều đó nghĩa là gì?'] },
  29: { sr: ['žalost zbog propuštene prilike', 'Šta kažeš kad plan propadne.'], fr: ['dommage', 'Ce qu’on dit quand un plan tombe à l’eau.', 'Quel dommage !'], es: ['lástima', 'Lo que dices cuando un plan se cae.', '¡Qué lástima!'], vi: ['tiếc quá', 'Điều bạn nói khi kế hoạch đổ bể.', 'Tiếc quá!'] },
  30: { sr: ['slike koje vidiš dok spavaš', 'Poželiš da budu "slatki" pred spavanje.'], fr: ['rêves', 'On les souhaite « doux » au coucher.', 'Fais de beaux rêves !'], es: ['sueños', 'Se desean «dulces» antes de dormir.', '¡Dulces sueños!'], vi: ['giấc mơ', 'Người ta chúc "ngọt ngào" trước khi ngủ.', 'Chúc ngủ ngon, mơ đẹp!'] },
}

export const TRANSLATIONS = TR

// The meaning, clue and example translation of a puzzle in the chosen language (falls back to English).
export function localized(puzzle, lang) {
  const t = lang !== 'en' && TR[puzzle.id]?.[lang]
  if (!t) return { english: puzzle.english, hint: puzzle.hint, en: puzzle.en }
  return { english: t[0], hint: t[1], en: t[2] || null }
}

export const COVERED_IDS = PUZZLES.map((p) => p.id)
