// English puzzles: [word, meaning, example sentence]. The meaning never contains the word.
export const EN = [
  ['HOUSE', 'a building where people live', 'We bought a small house by the sea.'],
  ['WATER', 'the clear liquid we drink', 'Please bring me a glass of water.'],
  ['LIGHT', 'brightness that lets you see', "Turn on the light, it's too dark."],
  ['HAPPY', 'feeling pleasure or joy', 'She was happy to see us.'],
  ['BREAD', 'baked food made from flour', 'I bought fresh bread this morning.'],
  ['PLANT', 'a living thing that grows in soil', 'Water the plant twice a week.'],
  ['DREAM', 'the images and stories your mind makes during sleep', 'Last night I had a strange dream.'],
  ['SMILE', 'a happy look on the face', 'Her smile made everyone relax.'],
  ['NIGHT', 'the dark part of the day', 'We talked late into the night.'],
  ['TRAIN', 'a vehicle that runs on rails', 'The train leaves at six.'],
  ['CLOUD', 'a white or gray mass floating in the sky', 'A dark cloud covered the sun.'],
  ['STORY', 'an account of events, real or imagined', 'Tell me a bedtime story.'],
  ['MUSIC', 'sounds arranged to be pleasant to hear', 'Turn the music up!'],
  ['EARTH', 'the planet we live on', 'The earth moves around the sun.'],
  ['HEART', 'the organ that pumps blood', 'My heart was beating fast.'],
  ['BEACH', 'a sandy shore beside the sea', 'We walked along the beach.'],
  ['CHAIR', 'a seat with a back, for one person', 'Pull up a chair and sit down.'],
  ['SWEET', 'tasting like sugar', 'This tea is too sweet.'],
  ['FRESH', 'new, clean, not old or stale', 'The air feels fresh after the rain.'],
  ['SLEEP', 'what you do at night with your eyes closed', 'I need more sleep.'],
  ['TIGER', 'a large striped wild cat', 'A tiger can swim.'],
  ['GRAPE', 'a small round fruit that grows in bunches', 'He ate a grape from the bunch.'],
  ['RIVER', 'a large stream of water flowing to the sea', 'The river flows through the town.'],
  ['PIZZA', 'a baked round dish with cheese and toppings', "Let's order a pizza tonight."],
  ['MONEY', 'what you use to buy things', "I'm saving money for a trip."],
  ['CANDY', 'a sweet food made with sugar', 'The kids ate too much candy.'],
  ['SMART', 'quick to learn; clever', 'That was a smart idea.'],
  ['BRAVE', 'ready to face danger or fear', 'The brave girl jumped in.'],
  ['LAUGH', 'to make sounds that show something is funny', 'His jokes always make me laugh.'],
  ['PEACE', 'calm, with no fighting or noise', 'They hoped for peace.'],
]
