// Spanish puzzles: [word with accents, meaning, example sentence]. Accents are ignored when guessing (Ñ is its own letter) and shown on the result.
export const ES = [
  ['AMIGO', 'persona con quien tienes amistad', 'Mi amigo vive en Madrid.'],
  ['LIBRO', 'objeto con páginas para leer', 'Este libro es muy interesante.'],
  ['PERRO', 'animal doméstico que ladra', 'El perro corre en el jardín.'],
  ['MUNDO', 'el planeta y todas las personas que lo habitan', 'Quiero viajar por el mundo.'],
  ['NOCHE', 'la parte oscura del día', 'Buenas noches, hasta mañana.'],
  ['PLAYA', 'orilla del mar con arena', 'Fuimos a la playa en verano.'],
  ['FELIZ', 'contento, alegre', 'Hoy me siento muy feliz.'],
  ['CIELO', 'lo que vemos arriba, azul de día', 'El cielo está despejado.'],
  ['FUEGO', 'llamas que dan luz y calor', 'Cuidado con el fuego.'],
  ['COMER', 'tomar alimentos', 'Vamos a comer a las dos.'],
  ['BEBER', 'tomar líquidos', 'Debes beber más agua.'],
  ['BAILE', 'movimiento del cuerpo al ritmo de la música', 'El baile empieza a las nueve.'],
  ['VERDE', 'color de la hierba', 'Prefiero la manzana verde.'],
  ['NEGRO', 'color de la noche sin luna', 'Lleva un abrigo negro.'],
  ['LUNES', 'primer día laborable de la semana', 'El lunes empiezo el curso.'],
  ['DULCE', 'con sabor a azúcar', 'Este pastel es muy dulce.'],
  ['CALLE', 'camino con casas a los lados', 'Vivo en esta calle.'],
  ['SUEÑO', 'imágenes que ves mientras duermes', 'Anoche tuve un sueño raro.'],
  ['NIÑOS', 'personas de pocos años', 'Los niños juegan en el patio.'],
  ['MUSEO', 'lugar donde se exponen obras de arte', 'Visitamos el museo el sábado.'],
  ['ÁRBOL', 'planta grande con tronco y ramas', 'Hay un pájaro en el árbol.'],
  ['HORAS', 'periodos de sesenta minutos', 'Trabajo ocho horas al día.'],
  ['TARDE', 'parte del día después del mediodía', 'Nos vemos esta tarde.'],
  ['LLAVE', 'objeto para abrir una puerta', 'No encuentro mi llave.'],
  ['MIRAR', 'dirigir los ojos hacia algo', 'Me gusta mirar las estrellas.'],
  ['NUBES', 'masas blancas o grises en el cielo', 'Hoy hay muchas nubes.'],
  ['PLATO', 'recipiente donde se sirve la comida', 'Pon el plato en la mesa.'],
  ['SILLA', 'asiento con respaldo para una persona', 'Siéntate en esta silla.'],
  ['TRIGO', 'cereal con el que se hace el pan', 'El pan se hace con harina de trigo.'],
  ['PAPEL', 'hoja delgada para escribir o dibujar', 'Necesito papel y lápiz.'],
]
