// French puzzles: [word with accents, meaning, example sentence]. Accents are ignored when guessing and shown on the result.
export const FR = [
  ['AMOUR', 'sentiment très fort d’affection', 'L’amour est plus fort que tout.'],
  ['TEMPS', 'la durée qui passe, ou la météo', 'Quel temps fait-il aujourd’hui ?'],
  ['TERRE', 'la planète où nous vivons, ou le sol', 'La Terre tourne autour du soleil.'],
  ['FLEUR', 'partie colorée d’une plante', 'Elle a offert une fleur à sa mère.'],
  ['LIVRE', 'objet avec des pages que l’on lit', 'J’ai lu ce livre en deux jours.'],
  ['NUAGE', 'masse blanche ou grise dans le ciel', 'Un gros nuage cache le soleil.'],
  ['PLAGE', 'bord de mer couvert de sable', 'On marche sur la plage.'],
  ['TABLE', 'meuble avec un plateau où l’on mange', 'Le dîner est sur la table.'],
  ['CHIEN', 'animal domestique qui aboie', 'Mon chien aime courir.'],
  ['FRUIT', 'aliment sucré qui pousse sur un arbre', 'Je mange un fruit chaque matin.'],
  ['JOUER', 's’amuser avec un jeu', 'Les enfants veulent jouer dehors.'],
  ['ÉCOLE', 'lieu où les enfants apprennent', 'Elle va à l’école à pied.'],
  ['FRÈRE', 'garçon qui a les mêmes parents que toi', 'Mon frère joue au football.'],
  ['TRAIN', 'véhicule qui roule sur des rails', 'Le train part à huit heures.'],
  ['ROUGE', 'couleur du sang et des tomates', 'Elle porte une robe rouge.'],
  ['DANSE', 'mouvements du corps en rythme avec la musique', 'J’adore la danse.'],
  ['RÊVER', 'voir des images pendant le sommeil', 'J’aime rêver de voyages.'],
  ['HEURE', 'soixante minutes', 'Quelle heure est-il ?'],
  ['SALUT', 'façon familière de dire bonjour', 'Salut ! Ça va ?'],
  ['JAUNE', 'couleur du citron', 'Le soleil est jaune.'],
  ['FORÊT', 'grand espace couvert d’arbres', 'Nous marchons dans la forêt.'],
  ['ÉCRAN', 'surface d’un téléphone ou d’une télévision', 'Mon écran est cassé.'],
  ['SUCRE', 'poudre douce que l’on met dans le café', 'Tu veux du sucre dans ton café ?'],
  ['FROID', 'le contraire de chaud', 'Il fait froid ce matin.'],
  ['GRAND', 'de taille importante', 'Il habite dans une grande ville.'],
  ['MERCI', 'mot de politesse pour dire qu’on est reconnaissant', 'Merci pour ton aide !'],
  ['NEIGE', 'pluie blanche et gelée de l’hiver', 'La neige couvre les montagnes.'],
  ['PLUIE', 'eau qui tombe du ciel', 'La pluie tombe depuis ce matin.'],
  ['PORTE', 'ce que l’on ouvre pour entrer', 'Ferme la porte, s’il te plaît.'],
  ['ARBRE', 'grande plante avec un tronc', 'Un oiseau chante dans l’arbre.'],
]
