// Serbian puzzles: [word, pronunciation, meaning in Serbian, example sentence, English meaning, English translation of the example].
// The English columns show on the result screen so learners still get a translation.
export const SR = [
  ["VOLIM", "VOH-leem", "osećam ljubav ili simpatiju", "Volim te.", "I love / I like", "I love you."],
  ["HVALA", "HVAH-lah", "izraz zahvalnosti", "Hvala ti puno.", "thank you", "Thank you very much."],
  ["DANAS", "DAH-nahs", "ovaj dan", "Šta radiš danas?", "today", "What are you doing today?"],
  ["SUTRA", "SOO-trah", "sledeći dan", "Vidimo se sutra.", "tomorrow", "See you tomorrow."],
  ["ŽIVOT", "ZHEE-voht", "vreme od rođenja do smrti", "Život je lep.", "life", "Life is beautiful."],
  ["SREĆA", "SREH-chah", "osećaj zadovoljstva; slučaj koji ide u prilog", "Sreća je u malim stvarima.", "luck / happiness", "Happiness is in the small things."],
  ["PRIČA", "PREE-chah", "pripovest; razgovor", "Kakva priča!", "story / chat", "What a story!"],
  ["KAFIĆ", "KAH-feech", "mesto gde se pije kafa", "Vidimo se u kafiću.", "café / bar", "See you at the café."],
  ["VREME", "VREH-meh", "sat ili stanje napolju (sunce, kiša)", "Kakvo je vreme danas?", "time / weather", "What's the weather like today?"],
  ["MOLIM", "MOH-leem", "ljubazna molba ili \"kako, izvolite?\"", "Molim te, pomozi mi.", "please / pardon", "Please, help me."],
  ["MAJKA", "MY-kah", "ženski roditelj", "Volim svoju majku.", "mother", "I love my mother."],
  ["DOBRO", "DOH-broh", "u redu; nije loše", "Sve je dobro.", "good / well / OK", "Everything is fine."],
  ["NOĆAS", "NOH-chahs", "večeras ili prošle noći", "Šta radiš noćas?", "tonight", "What are you doing tonight?"],
  ["JUTRO", "YOO-troh", "početak dana", "Dobro jutro!", "morning", "Good morning!"],
  ["SLIKA", "SLEE-kah", "fotografija ili crtež", "Pošalji mi sliku.", "picture / photo", "Send me a picture."],
  ["MLEKO", "MLEH-koh", "bela tečnost koju daju krave", "Kupi mleko.", "milk", "Buy milk."],
  ["TAČNO", "TAHCH-noh", "ispravno; baš tako", "Tačno tako!", "exactly / correct", "Exactly!"],
  ["MOŽDA", "MOHZH-dah", "verovatno, nije sigurno", "Možda sutra.", "maybe", "Maybe tomorrow."],
  ["MNOGO", "MNOH-goh", "u velikoj meri; puno", "Mnogo hvala!", "a lot / very", "Thanks a lot!"],
  ["ČESTO", "CHEHS-toh", "mnogo puta; ne retko", "Često mislim na tebe.", "often", "I often think of you."],
  ["KASNO", "KAHS-noh", "posle predviđenog vremena", "Kasno je.", "late", "It's late."],
  ["SPORO", "SPOH-roh", "malom brzinom", "Govori sporo, molim te.", "slowly", "Speak slowly, please."],
  ["DRAGA", "DRAH-gah", "voljena žena (obraćanje)", "Laku noć, draga.", "dear (to a woman)", "Good night, dear."],
  ["GLAVA", "GLAH-vah", "deo tela iznad vrata", "Boli me glava.", "head", "My head hurts."],
  ["ČEKAM", "CHEH-kahm", "ostajem tu dok neko ne dođe", "Čekam te ispred.", "I'm waiting", "I'm waiting for you outside."],
  ["IDEMO", "EE-deh-moh", "krećemo; hajde", "Idemo na kafu?", "we're going / let's go", "Shall we go for coffee?"],
  ["ŽELIM", "ZHEH-leem", "hoću; priželjkujem", "Želim ti sve najbolje.", "I wish / I want", "I wish you all the best."],
  ["ZNAČI", "ZNAH-chee", "ima smisao", "Šta to znači?", "means", "What does that mean?"],
  ["ŠTETA", "SHTEH-tah", "žalost zbog propuštene prilike", "Kakva šteta!", "pity / shame", "What a pity!"],
  ["SNOVI", "SNOH-vee", "slike koje vidiš dok spavaš", "Slatki snovi!", "dreams", "Sweet dreams!"],
]

