// Vietnamese puzzles: [word with tone marks, meaning, example sentence].
// Guesses ignore the tone marks (sắc, huyền, hỏi, ngã, nặng) but keep ă â ê ô ơ ư đ as their own letters; the tones show on the result.
export const VI = [
  ['NGƯỜI', 'một cá nhân, nam hay nữ', 'Anh ấy là người tốt.'],
  ['TIẾNG', 'âm thanh, hoặc ngôn ngữ của một nước', 'Tôi đang học tiếng Việt.'],
  ['KHÔNG', 'từ dùng để phủ định', 'Tôi không biết.'],
  ['ĐƯỜNG', 'lối đi cho xe và người', 'Con đường này rất dài.'],
  ['THÍCH', 'có cảm tình, ưa', 'Em thích uống cà phê.'],
  ['CHIỀU', 'buổi sau trưa, trước tối', 'Chiều nay mình đi chơi nhé.'],
  ['NHIỀU', 'số lượng lớn', 'Hôm nay có nhiều mây.'],
  ['NGOÀI', 'phía không ở bên trong', 'Ngoài trời đang mưa.'],
  ['XUỐNG', 'di chuyển về phía thấp hơn', 'Chúng ta xuống xe ở đây.'],
  ['TRĂNG', 'vật sáng trên bầu trời ban đêm', 'Đêm nay trăng rất tròn.'],
  ['NGHĨA', 'ý của một từ hay một câu', 'Từ này có nghĩa là gì?'],
  ['CHUỐI', 'loại quả dài, vỏ màu vàng', 'Bé thích ăn chuối.'],
  ['GƯƠNG', 'tấm kính để soi hình mình', 'Cô ấy soi gương mỗi sáng.'],
  ['CHÚNG', 'từ chỉ nhiều người hoặc nhiều vật', 'Chúng tôi đi học cùng nhau.'],
  ['NHANH', 'tốc độ cao, không chậm', 'Xe chạy rất nhanh.'],
  ['TRƯỚC', 'ở phía đầu, hoặc xảy ra sớm hơn', 'Hãy rửa tay trước khi ăn.'],
  ['NHỮNG', 'từ đặt trước danh từ để chỉ số nhiều', 'Những bông hoa này rất đẹp.'],
  ['TUYẾT', 'nước đóng băng rơi từ trời mùa đông', 'Mùa đông có tuyết rơi.'],
  ['KHÁCH', 'người đến thăm nhà hoặc mua hàng', 'Khách đến nhà rất đông.'],
  ['NGHÈO', 'ít tiền, không giàu', 'Ngày xưa nhà họ rất nghèo.'],
  ['THUỐC', 'chất dùng để chữa bệnh', 'Uống thuốc sau khi ăn.'],
  ['CHUỘT', 'con vật nhỏ hay gặm đồ đạc', 'Con chuột chạy vào hang.'],
  ['CHIẾC', 'từ chỉ đơn vị cho đồ vật', 'Chiếc xe này màu đỏ.'],
  ['THÁNG', 'một trong mười hai phần của năm', 'Tháng này trời rất nóng.'],
  ['TRONG', 'ở phía không phải bên ngoài', 'Mẹ đang ở trong bếp.'],
  ['KHUYA', 'rất muộn trong đêm', 'Đã khuya rồi, đi ngủ thôi.'],
]
